### ISSUE TITLE
CORS and client applications actuator endpoints are secured with basic Auth

### ISSUE THREAD

**Issue by rahulkas123** [codecentric/spring-boot-admin#1691]
Hi,

I am trying to get to instances/{id}/details page for one of the client applications.
This client applications we have is having different domain url . This is causing the browser to make a preflight request and actual GET request to client application directly bypassing the Spring boot admin server. Since, JS is handling all these calls the Authorization headers are not added to JS call and we get 401 error. Even if I disable the basic auth on client application I see a 302 in admin server chrome network tab and page doesn't load up .

Is there any way we can handle this situation ?

**Comment by nickcaballero** [comment]
Is this a custom UI? Generally the request to the instance should go through the SBA instance proxy.

**Comment by rahulkas123** [comment]
This is not a custom UI .  All other applications with the same domain url like admin server work fine.

**Comment by izeye** [comment]
This seems to be intended to be closed via 875cc286a4be089aa5f39c8b54a99405beba2f92 based on its commit message.

**Comment by SteKoe** [comment]
Hi @rahulkas123, 

please update Spring Boot Admin (client and server) to the latest version (2.4.1) and use Spring Boot >= 2.4.3. This should fix the issue.

**Comment by SeifBh** [comment]
@SteKoe , that does not solve the problem for me !

**Comment by klasker** [comment]
I still see this problem, too. I have instructed my client app (on port 8888) to allow for CORS but the  SBA UI is throwing these exceptions. I am using version 2.4.1.
![image006](https://user-images.githubusercontent.com/2480008/125132234-a965c700-e0c9-11eb-81d1-ac61e0345b04.jpg)

**Comment by rahulkas123** [comment]
I am still having this issue.

**Comment by aurelius1989** [comment]
I have the same issue described above and the fact is that this post does not help that much, has the discussion moved to a different thread, if so please share the link.

**Comment by ulischulte** [comment]
@aurelius, since we're not able to point out the real problem, we need something to be able to reproduce the problem. Is SBA running behind a frontend proxy? If so, could you provide your configuration? Maybe you could also provide a sample project to generally reproduce the issue.

**Comment by aurelius1989** [comment]
Ok, I will provide the details here:

`@EnableAdminServer
@SpringBootApplication
public class OppPuteServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(OppPuteServiceApplication.class, args);
    }
}`

`@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private Environment environment;

    private final AdminServerProperties adminServer;

    public WebSecurityConfig(AdminServerProperties adminServer) {
        this.adminServer = adminServer;
    }

    @Bean("authenticationManager")
    @Override
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication()
                .withUser(environment.getProperty("spring.security.user.name"))
                .password("{noop}" + environment.getProperty("spring.security.user.password"))
                .roles("USER");
    }

    @Override
    protected void configure(final HttpSecurity https) throws Exception {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");
        successHandler.setDefaultTargetUrl(this.adminServer.getContextPath() + "/applications");
        successHandler.setAlwaysUseDefaultTargetUrl(true);
        https
                .cors()
                .and()
                .authorizeRequests()
                .antMatchers(this.adminServer.getContextPath() + "/assets/**").permitAll()
                .antMatchers(this.adminServer.getContextPath() + "/login").permitAll()
                .antMatchers(this.adminServer.getContextPath() + "/logout").permitAll()
                .antMatchers(this.adminServer.getContextPath() + "/management/**").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                .loginPage(this.adminServer.getContextPath() + "/login")
                .successHandler(successHandler)
                .and()
                .logout()
                .deleteCookies("JSESSIONID")
                .logoutUrl(this.adminServer.getContextPath() + "/logout")
                .logoutSuccessUrl(this.adminServer.getContextPath() + "/login")
                .and()
                .csrf()
                .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                .ignoringRequestMatchers(
                        new AntPathRequestMatcher(this.adminServer.getContextPath() +
                                "/instances", HttpMethod.POST.toString()),
                        new AntPathRequestMatcher(this.adminServer.getContextPath() +
                                "/instances/*", HttpMethod.DELETE.toString()),
                        new AntPathRequestMatcher(this.adminServer.getContextPath() + "/management/**"))
                .and()
                .rememberMe((rememberMe) -> rememberMe.key(UUID.randomUUID().toString()).tokenValiditySeconds(1209600))
                .httpBasic();
    }

    @Bean
    CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(Arrays.asList(CorsConfiguration.ALL));
        configuration.setAllowedMethods(Arrays.asList("GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS"));
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }

    @Bean
    public CORSFilter corsFilter() {
        CorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.addAllowedOrigin(CorsConfiguration.ALL);
        ((UrlBasedCorsConfigurationSource) source).registerCorsConfiguration("/**", config);
        return new CORSFilter(source);
    }
}`

`buildscript {
    ext {
        springBootVersion = '2.4.3'
    }
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://artifactory.metrosystems.net/artifactory/plugins-release" }
        jcenter()

    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("de.metro:gradle-docker-plugin:1.+")
        classpath("au.com.dius:pact-jvm-provider-gradle_2.11:3.3.3")
        classpath("net.ltgt.gradle:gradle-apt-plugin:0.3")
        classpath("com.commercehub.gradle.plugin:gradle-avro-plugin:0.9.0")
    }
}

project.ext {
...
}

apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'docker'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

jar {
    baseName = 'pute-service'
    version = '0.0.1-SNAPSHOT'
}

sourceCompatibility = 1.8

mainClassName = 'de.metro.betty.opp.pute.OppPuteServiceApplication'
bootJar.enabled = false
bootDistZip.enabled = false
bootDistTar.enabled = false
jar.enabled = true

applicationName = "betty_pickandpack_pute"

repositories {
    mavenCentral()
    maven { url "https://artifactory.metrosystems.net/artifactory/libs-release" }
    jcenter()
}

dependencies {
    compile 'de.codecentric:spring-boot-admin-starter-server:2.4.1'
    compile 'de.codecentric:spring-boot-admin-server-ui:2.4.1'
    compile 'de.codecentric:spring-boot-admin-server:2.4.1'
    compile 'org.springframework.boot:spring-boot-starter-web'
    compile 'org.springframework.boot:spring-boot-starter-actuator'
    compile 'org.springframework.boot:spring-boot-starter-security'
    compile('net.logstash.logback:logstash-logback-encoder:5.2')
}


bootRun {
    // change to prod if you want to test the json based prod logging
    jvmArgs = [ '-Dspring.profiles.active=dockermachine' ]
}

task clean_build_dir(type: Exec) {
    commandLine 'rm', '-rf', 'build'
}

clean.dependsOn << [clean_build_dir]

dockerBuild.dependsOn << [build]
`

`service.vertical=pickandpack
service.name=pute
service.base-path=/${service.vertical}.${service.name}.v1

spring.boot.admin.context-path=${service.base-path}
spring.boot.admin.ui.public-url=${service.base-path}

# take this as the default profile if not overwritten
spring.profiles.default=containerized
management.security.enabled=true

server.port=${SERVICE_PORT:8017}
server.address=${SERVICE_IP:0.0.0.0}

# metrics config
metrics.jvm.enabled=${JVM_METRICS_ENABLED:true}

# k8s/pod config
k8s.secret.token.path=${SECRET_TOKEN_PATH:/var/run/secrets/kubernetes.io/serviceaccount/token}
k8s.pod.name=${HOSTNAME:unkown_pod_name}
k8s.service.port=${KUBERNETES_SERVICE_PORT}
k8s.service.host=${KUBERNETES_SERVICE_HOST}
k8s.betty.keystore=keyStore.jks
k8s.betty.keystore.password=${KEYSTORE_PASSWORD}

# authentication of other spring boot services against this service
spring.security.user.name=${ADMIN_USER:admin}
spring.security.user.password=${ADMIN_PW:badpa}

service.web-client.service-uri.health=${spring.boot.admin.client.instance.health-url}
management.endpoints.web.base-path=${service.base-path}/management
management.endpoints.web.exposure.include=health,heapdump,info,logfile,loggers,metrics,threaddump,configprops,env,httptrace`

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: opp-pute
  namespace: default
  annotations:
    noHealthCheckMonitoring: "true"
  labels:
    product: mfulfillpp
    vertical: pickandpack
    service: pute
    kind: interactive
spec:
  replicas: ${OPP_PUTE_REPLICATION_FACTOR}
  selector:
    matchLabels:
      name: opp-pute
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 0
  template:
    metadata:
      name: opp-pute
      labels:
        product: mfulfillpp
        name: opp-pute
        vertical: pickandpack
        service: pute
        kind: interactive
    spec:
      containers:
        - name : opp-pute
          image: ${HARBOR_DOCKER_REGISTRY_OPP}/betty_pickandpack_pute:${HASH}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: ${COMMON_SPRING_BOOT_SERVICE_CPU_LIMIT}
              memory: ${COMMON_SPRING_BOOT_SERVICE_MEMORY_LIMIT}
            requests:
              cpu: ${COMMON_SPRING_BOOT_SERVICE_CPU_REQUEST}
              memory: ${COMMON_SPRING_BOOT_SERVICE_MEMORY_REQUEST}
          readinessProbe:
            httpGet:
              path: /pickandpack.pute.v1/management/health
              port: 8017
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /pickandpack.pute.v1/management/health
              port: 8017
            initialDelaySeconds: 180
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /opt/kafka-temp
            name: kafka-temp
          env:
          - name: JAVA_OPTS
            value: "${OPP_COMMON_JAVA_OPTS} ${OPP_COMMON_HEAPDUMP_OPTS} ${OPP_COMMON_JAVA_MEM_OPTS} ${OPP_SPRING_PROFILE} $DD_JAVA_OPTS"
          - name: SERVICE_PORT
            value: "8017"
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opp-keystore
                key: password
          - name: DATADOG_ENABLED
            value: "true"
          - name: DATADOG_API_KEY
            value: "{{datadog.api_key}}"
          - name: KAFKA_CACHE_FOLDER
            value: "/opt/kafka-temp"
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: opp-springadmin
                key: username
          - name: ADMIN_PW
            valueFrom:
              secretKeyRef:
                name: opp-springadmin
                key: password
          - name: PUBLIC_URL
            value: ${PICKANDPACK_PUTE_PUBLIC_URL}
          ports:
          - containerPort: 8017
            protocol: TCP
            name: opp-pute

      volumes:
          - name: kafka-temp
            emptyDir: {}

      restartPolicy: Always
      nodeSelector:
        kind: interactive
`

**Comment by aurelius1989** [comment]
Ok, I will provide the details here:

MAIN CLASS
```
@EnableAdminServer
@SpringBootApplication
public class AdminServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(AdminServiceApplication.class, args);
    }
}
```

WebSecurityConfig
```
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private Environment environment;

    private final AdminServerProperties adminServer;

    public WebSecurityConfig(AdminServerProperties adminServer) {
        this.adminServer = adminServer;
    }

    @Bean("authenticationManager")
    @Override
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication()
                .withUser(environment.getProperty("spring.security.user.name"))
                .password("{noop}" + environment.getProperty("spring.security.user.password"))
                .roles("USER");
    }

    @Override
    protected void configure(final HttpSecurity https) throws Exception {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");
        successHandler.setDefaultTargetUrl(this.adminServer.getContextPath() + "/applications");
        successHandler.setAlwaysUseDefaultTargetUrl(true);
        https
                .cors()
                .and()
                .authorizeRequests()
                .antMatchers(this.adminServer.getContextPath() + "/assets/**").permitAll()
                .antMatchers(this.adminServer.getContextPath() + "/login").permitAll()
                .antMatchers(this.adminServer.getContextPath() + "/logout").permitAll()
                .antMatchers(this.adminServer.getContextPath() + "/management/**").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin()
                .loginPage(this.adminServer.getContextPath() + "/login")
                .successHandler(successHandler)
                .and()
                .logout()
                .deleteCookies("JSESSIONID")
                .logoutUrl(this.adminServer.getContextPath() + "/logout")
                .logoutSuccessUrl(this.adminServer.getContextPath() + "/login")
                .and()
                .csrf()
                .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                .ignoringRequestMatchers(
                        new AntPathRequestMatcher(this.adminServer.getContextPath() +
                                "/instances", HttpMethod.POST.toString()),
                        new AntPathRequestMatcher(this.adminServer.getContextPath() +
                                "/instances/*", HttpMethod.DELETE.toString()),
                        new AntPathRequestMatcher(this.adminServer.getContextPath() + "/management/**"))
                .and()
                .rememberMe((rememberMe) -> rememberMe.key(UUID.randomUUID().toString()).tokenValiditySeconds(1209600))
                .httpBasic();
    }

    @Bean
    CorsConfigurationSource corsConfigurationSource() {
        CorsConfiguration configuration = new CorsConfiguration();
        configuration.setAllowedOrigins(Arrays.asList(CorsConfiguration.ALL));
        configuration.setAllowedMethods(Arrays.asList("GET", "PUT", "POST", "PATCH", "DELETE", "OPTIONS"));
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", configuration);
        return source;
    }

    @Bean
    public CORSFilter corsFilter() {
        CorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.addAllowedOrigin(CorsConfiguration.ALL);
        ((UrlBasedCorsConfigurationSource) source).registerCorsConfiguration("/**", config);
        return new CORSFilter(source);
    }
}

**Comment by aurelius1989** [comment]
I also want to add that SBA it's deployed in a k8s environment as type deployment.

**Comment by aurelius1989** [comment]
finally managed to fix it by adding a custom cors filter
`@Configuration
@Order(Ordered.HIGHEST_PRECEDENCE)
public class CORSFilter extends CorsFilter {

    public CORSFilter(CorsConfigurationSource source) {
        super(source);
    }

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {

        response.setHeader("Access-Control-Allow-Origin", "*");
        response.setHeader("Access-Control-Allow-Credentials", "true");
        response.setHeader("Access-Control-Allow-Methods",
                "ACL, CANCEL, UPLOAD, CHECKIN, CHECKOUT, COPY, DELETE, GET, HEAD, LOCK, MKCALENDAR, MKCOL, MOVE, OPTIONS, POST, PROPFIND, PROPPATCH, PUT, REPORT, SEARCH, UNCHECKOUT, UNLOCK, UPDATE, VERSION-CONTROL");
        response.setHeader("Access-Control-Max-Age", "3600");
        response.setHeader("Access-Control-Allow-Headers",
                "Origin, X-Requested-With, Content-Type, Accept, Key, Authorization");

        if ("OPTIONS".equalsIgnoreCase(request.getMethod())) {
            response.setStatus(HttpServletResponse.SC_OK);
        } else {
            filterChain.doFilter(request, response);
        }
    }

}`
