### ISSUE TITLE
Spring Boot Admin incompatible with released Spring Boot 3.0.0-M1

### ISSUE THREAD

**Issue by patpatpat123** [codecentric/spring-boot-admin#1974]
Hello Spring Boot Admin Team,

Just wanted to highlight some facts:
- This project is amazing
- I upgraded my Spring Boot Admin Server using Spring Boot 3.0.0-M1, since it is officially released:
https://spring.io/blog/2022/01/20/spring-boot-3-0-0-m1-is-now-available

Unfortunately, SBAServer will fail to start up, as SBA is mainly relying on ```javax```
Is it possible to resolve this issue and have a SBA compatible with the on-the-roadmap Java 17 + Spring Boot 3.x please?

Thank you

**Comment by erikpetzold** [comment]
Hi,

we have that topic on our list and there already is a branch for the upgrade, but this will take some time (GA of Spring Boot 3 is planned for November as far as I know).

First step was upgrade to java 17, next will be spring boot 3 including jakarta enterprise packages, then changed actuators (if any).

If anyone wants to contribute you can file a pull request against `experimental/spring-boot-3-playground` branch

**Comment by ulischulte** [comment]
Hi,
we're making progress, but there are still a few challenges to overcome.
Wiremock, for instance, does not yet support jetty 11 (https://github.com/wiremock/wiremock/issues/1760).
Spring Boot 3, however, only supports jetty 11. -.-

**Comment by erikpetzold** [comment]
Still having issues with nexus-staging-maven-plugin, https://issues.sonatype.org/browse/NEXUS-27902

update did not help, will try workaround next

**Comment by SteKoe** [comment]
Since we have already release the first Milestones of SBA supporting Spring Boot 3, this issue is resolved.

**Comment by dgo312** [comment]
i have updated spring boot 3..0.0 but my test case are failing please find below error
 <mockito.version>4.8.1</mockito.version>
        <wiremock.version>2.27.2</wiremock.version>

java.lang.NoClassDefFoundError: Could not initialize class com.github.tomakehurst.wiremock.jetty9.JettyHttpServerFactory
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: javax/servlet/DispatcherType [in thread "main"

can you please tell  me how to reolve this

**Comment by SianK-WP** [comment]
Hello! We are having a similar issue after updating to Spring Boot 3, we have tried the same fixes as suggested in other threads "wiremock-jre8-standalone" and this has not solved the issue for us. Any help on getting this resolved would be appreciated.
