### ISSUE TITLE
UI not fully functional if running at custom context-path.

### ISSUE THREAD

**Issue by ztomic** [codecentric/spring-boot-admin#2175]
## Spring Boot Admin Server information

- **Version**:
  3.0.0-M7

- **Spring Boot version**:
  3.0.0

- **Configured Security**:
  

- **Webflux or Servlet application**:
  servlet

With new version, if it is running on non-default context-path, e.g.:

```yaml
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: Eureka Dashboard
            url: ${eureka.dashboard.path}
            iframe: true        
      context-path: /spring-boot-admin
```

Page refresh in browser, back button, etc. are not working, external views also are not working.

**Comment by erikpetzold** [comment]
Hi @ztomic 
we have not looked into details of your issue yet, but today there was a release of 3.0.0-M6 and it includes some changes to context-path handling. Maybe you can check if it is working with that version now?

**Comment by ztomic** [comment]
Hi @erikpetzold 
I have checked with 3.0.0-M6, it is still the same. Here is sample application: https://github.com/ztomic/spring-boot-admin-sample
You can start discovery application and open http://localhost:8888, it should redirect you to http://localhost:8888/spring-boot-admin/applications and if you click refresh in browser 404 is returned.

**Comment by ulischulte** [comment]
The bug should be fixed with Version 3.0.0-M8

**Comment by ztomic** [comment]
It is partially fixed. Navigation is OK but external views in iframe still are not working, in console is same error as commented before:
![image](https://user-images.githubusercontent.com/1428972/209349841-b6c36045-4865-4296-9bf8-79af38ea367a.png)

**Comment by andrew2184** [comment]
Hi, I'm also having the same issue when trying to render an external page and setting "iframe=true": 

![image](https://user-images.githubusercontent.com/3290478/224918158-17455b6f-ddda-4a12-93c9-343109db6e67.png)
