### ISSUE TITLE
Start sequence

### ISSUE THREAD

**Issue by lhy507613824** [codecentric/spring-boot-admin#2201]
hello developer, my project use Spring Boot3.0.0, Spring Boot Admin3.0.0-M4, Spring Cloud Alibaba Nacos Discovery. I have doubts about the order in which apps are launched, I have two applications: AdminServer and User, The effects of their different startup sequences are as follows

| Start sequence                         | Result                      |
| -------------------------------------- | --------------------------- |
| AdminServer->User                      | No applications registered. |
| User->AdminServer                      | User                        |
| User->AdminServer->Restart AdminServer | User, AdminServer           |

Spring Boot Admin need to be started last?
Thanks!

**Comment by SteKoe** [comment]
Hi,

please update your Spring Boot Admin to M8 and check again. We have fixed a bug that addresses the issue you report.

Regards,
SteKoe

**Comment by lhy507613824** [comment]
> Hi,
> 
> please update your Spring Boot Admin to M8 and check again. We have fixed a bug that addresses the issue you report.
> 
> Regards, SteKoe

Hi SteKoe, This is my modified pom file, still have this problem
```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2022.0.0-RC3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2022.0.0.0-RC1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>de.codecentric</groupId>
                <artifactId>spring-boot-admin-dependencies</artifactId>
                <version>3.0.0-M8</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by ulischulte** [comment]
@lhy507613824 ,

have you tried setting spring.cloud.nacos.discovery.watch.enabled to true? The default used to be true, but now it's false.

Have you added @EnableScheduling to the main Application class of your Spring Boot Admin implementation?

Regards
Uli

**Comment by lhy507613824** [comment]
> ```
> spring-boot-admin
> ```
I did what you said and upgrade spring-boot-admin-dependencies to 3.0.2, problem still exists

**Comment by lhy507613824** [comment]
> @lhy507613824 ,
> 
> have you tried setting spring.cloud.nacos.discovery.watch.enabled to true? The default used to be true, but now it's false. (old configuration properties: https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery-en#more-information-about-nacos-discovery-starter-configurations vs new configuration properties: https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme.md#more)
> 
> Have you added @EnableScheduling to the main Application class of your Spring Boot Admin implementation?
> 
> Regards Uli

I did what you said and upgrade spring-boot-admin-dependencies to 3.0.2, problem still exists

**Comment by karl-chanel** [comment]
Encountered the same issue, Do what you said and @ still not fixed.@ulischulte

**Comment by ChinaJeckXu** [comment]
我也遇到了这个问题，Spring Boot 2.7.10，Spring Cloud 2021.0.5，Spring Cloud Alibaba 2021.0.5.0，Spring Boot Admin 2.7.10

**Comment by MorganArthur** [comment]
我的版本是 Spring Boot 3.0.4，Spring Cloud 2022.0.1，Spring Cloud Alibaba 2022.0.0.0-RC1，Spring Boot Admin 3.0.2，也有这个问题，另外还发现的是如果我只启动了spring boot admin，访问页面的时候不会发现任务服务（但实际应该发现spring boot admin自身服务才对），我先启动别的服务，在启动spring boot admin时，才会发现自身服务

**Comment by ulischulte** [comment]
Since we are all not polyglots - it would be very helpful to keep issues and their discussion in English.

**Comment by erikpetzold** [comment]
This seems to be a bug in spring cloud with nacos, see #2390
